name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust/takavalo/

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose

